import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/tokyonight_moon.toml"
  # "~/.config/alacritty/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13.0


[font.bold]
family = "JetBrainsMono Nerd Font"
# family = "Google Sans Code"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# family = "Google Sans Code"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "Google Sans Code"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Google Sans Code"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font"
style = "Regular"
